[package]
name = "hecate"
version = "0.3.0"
authors = ["ingalls <ingalls@protonmail.com>"]

[dependencies]
rand = "0.4"
tempdir = "0.3"
base64 = "~0.9.0"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.6"
geo = "0.6.3"
geojson="0.9.1"
postgres = "0.15.1"
quick-xml = "0.11.0"
serde_json = "1.0"
r2d2 = "0.8.2"
r2d2_postgres = "0.14.0"
env_logger = "0.5"
fallible-iterator = "0.1.x"

[dependencies.clap]
features = ["yaml"]
version = "2.29.2

[[bin]]
name = "hecate"
doc = false
