[package]
name = "hecate"
version = "0.2.0"
authors = ["ingalls <ingalls@protonmail.com>"]

[dependencies]
base64 = "~0.9.0"
rocket = "0.3"
rocket_codegen = "0.3.5"
rocket_contrib = "0.3.5"
geo = "0.6.3"
geojson="0.9.1"
postgres = "0.15.1"
quick-xml = "0.10.1"
serde_json = "1.0"
r2d2 = "0.8.1"
r2d2_postgres = "0.14.0"
env_logger = "0.4"
fallible-iterator = "0.1.x"

[dependencies.clap]
features = ["yaml"]
version = "2.19.0"

[[bin]]
name = "hecate"
doc = false
