[package]
name = "hecate"
version = "0.1.2"
authors = ["ingalls <ingalls@protonmail.com>"]

[dependencies]
staticfile = "0.5.0"
geo = "0.6.3"
iron = "0.6.0"
router = "0.6.0"
mount = "0.4.0"
geojson="0.9.1"
urlencoded = "0.6.0"
postgres = "0.15.1"
quick-xml = "0.10.1"
persistent = "0.4.0"
serde_json = "1.0"
r2d2 = "0.8.1"
r2d2_postgres = "0.14.0"
logger = "0.4.0"
env_logger = "0.4"

[dependencies.clap]
features = ["yaml"]
version = "2.19.0"

[[bin]]
name = "hecate"
doc = false
