version: 2

jobs:
    build:
        docker:
            - image: ubuntu:18.04
            - image: mdillon/postgis:11
        resource_class: xlarge
        steps:
            - run:
                name: "Add ubuntu-toolchain"
                command: |
                    apt-get update -y \
                    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
                        software-properties-common \
                        libcurl4-openssl-dev \
                        apt-transport-https \
                        postgresql-contrib \
                        build-essential \
                        libiberty-dev \
                        binutils-dev \
                        pkg-config \
                        zlib1g-dev \
                        postgresql \
                        libssl-dev \
                        libelf-dev \
                        libdw-dev \
                        locales \
                        postgis \
                        openssl \
                        cmake \
                        curl \
                        wget \
                        git \
                        gcc \
                        git \
                    && locale-gen en_US.UTF-8 \
                    && bash -c "echo \"America/New_York\" > /etc/timezone"
            - checkout
            - run:
                name: "Install node"
                command: |
                  curl 'https://nodejs.org/dist/v10.15.3/node-v10.15.3-linux-x64.tar.gz' | tar -xzv \
                  && cp ./node-v10.15.3-linux-x64/bin/node /usr/bin/ \
                  && ./node-v10.15.3-linux-x64/bin/npm install -g npm
            - run:
                name: "Install rust"
                command: |
                  curl https://sh.rustup.rs -sSf > /tmp/rustup.sh \
                  && sh /tmp/rustup.sh -y --default-toolchain nightly-2019-06-01 \
                  && echo "export PATH=$HOME/.cargo/bin:$PATH" >> $BASH_ENV
            - run:
                name: "Run tests"
                command: ./tests/test.sh
            - run:
                name: "npm install"
                command: cd ci && npm install
            - run:
                name: "Publish Release"
                command: ./ci/publish.sh

workflows:
    version: 2
    build:
        jobs:
            - build:
                filters:
                    tags:
                        only: /.*/
