version: 2

jobs:
    build:
        docker:
            - image: ubuntu:18.04
            # - image: mdillon/postgis:11
        resource_class: large
        steps:
            - run:
                name: "Add ubuntu-toolchain"
                command: |
                    apt-get update -y \
                    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
                        software-properties-common \
                        libcurl4-openssl-dev \
                        apt-transport-https \
                        postgresql-contrib \
                        build-essential \
                        libiberty-dev \
                        binutils-dev \
                        pkg-config \
                        zlib1g-dev \
                        postgresql \
                        libssl-dev \
                        libelf-dev \
                        libdw-dev \
                        locales \
                        postgis \
                        openssl \
                        cmake \
                        curl \
                        wget \
                        git \
                        gcc \
                        git \
                    && locale-gen en_US.UTF-8 \
                    && bash -c "echo \"America/New_York\" > /etc/timezone"
            - checkout
            - run:
                name: "Install rust"
                command: |
                  curl https://sh.rustup.rs -sSf > /tmp/rustup.sh \
                  && sh /tmp/rustup.sh -y --default-toolchain nightly-2019-06-01 \
                  && echo "export PATH=$HOME/.cargo/bin:$PATH" >> $BASH_ENV
            # - run:
            #     name: "Run tests"
            #     command: ./tests/test.sh
            - run:
                name: "Publish Release"
                command: ./scripts/publish.sh

# RUN rm /bin/sh && ln -s /bin/bash /bin/sh
# ENV SHELL /bin/bash

# RUN echo "local all all trust " > /etc/postgresql/10/main/pg_hba.conf \
#     && echo "host all all 127.0.0.1/32 trust" >> /etc/postgresql/10/main/pg_hba.conf \
#     && echo "host all all ::1/128 trust" >> /etc/postgresql/10/main/pg_hba.conf

workflows:
    version: 2
    build:
        jobs:
            - build:
                filters:
                    tags:
                        only: /.*/
