[package]
publish = false
name = "hecate_derive"
version = "0.1.0"
edition = "2021"
authors = ["ingalls <ingalls@protonmail.com>"]
license = "MIT"
description = "Custom Derivable traits used in Hecate Server"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
[dependencies.syn]
version = "1.0"
features = [
    "derive"
]
