# API

# Group Server

## GET /
+ Response 200 (text/plain)

        Hello World!

## Meta [/api/meta/{key}]

+ Parameters
    + key: name (String) - A unique key for referencing a value

### Metadata [POST]

+ Response 200 (text/plain)
    + Body

                Test Response

### Metadata [GET]

+ Response 200 (text/plain)
    + Body

                Test Response

### Metadata [DELETE]

+ Response 200 (text/plain)
    + Body

                Test Response
