name: Release Binary

on:
    release:
        types:
            - created

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Build Hecate
              run: cargo build --release
            - name: Upload Release
              id: upload-release-asset
              uses: actions/upload-release-asset@v1.0.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ./target/release/hecate
                  asset_name: hecate_linux
