name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Build
      run: docker build -t test .
    - name: Run tests
      run: docker run test
